### ISSUE TITLE
use it in react native, get error

### ISSUE THREAD

**Issue by guitar9** [public-transport/hafas-client#52]
Somebody has used in react native?
I get following error:

```
The development server returned response error code: 500

URL: http://localhost:8081/index.delta?platform=android&dev=true&minify=false&deltaBundleId=9083ef9957029468

Body:
{"originModulePath":"/home/t/ws/react/pendler/node_modules/hafas-client/lib/request.js","targetModuleName":"crypto","message":"Unable to resolve module `crypto` from `/home/t/ws/react/pendler/node_modules/hafas-client/lib/request.js`: Module `crypto` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.","errors":[{"description":"Unable to resolve module `crypto` from `/home/t/ws/react/pendler/node_modules/hafas-client/lib/request.js`: Module `crypto` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`."}],"name":"Error","stack":"Error: Unable to resolve module `crypto` from `/home/t/ws/react/pendler/node_modules/hafas-client/lib/request.js`: Module `crypto` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\n    at ModuleResolver.resolveDependency (/home/t/ws/react/pendler/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:1460)\n    at ResolutionRequest.resolveDependency (/home/t/ws/react/pendler/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)\n    at DependencyGraph.resolveDependency (/home/t/ws/react/pendler/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)\n    at dependencies.map.relativePath (/home/t/ws/react/pendler/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)\n    at Array.map (native)\n    at resolveDependencies (/home/t/ws/react/pendler/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)\n    at /home/t/ws/react/pendler/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33\n    at Generator.next (<anonymous>)\n    at step (/home/t/ws/react/pendler/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)\n    at /home/t/ws/react/pendler/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473"}
processBundleResult
    BundleDownloader.java:266
access$200
    BundleDownloader.java:35
onResponse
    BundleDownloader.java:153
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1133
run
    ThreadPoolExecutor.java:607
run
    Thread.java:762

```

**Comment by derhuerst** [comment]
The essential part of the error message seems this one:

```
Unable to resolve module `crypto` from `/home/t/ws/react/pendler/node_modules/hafas-client/lib/request.js`: Module `crypto` does not exist in the Haste module map
This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
```

Have you tried this?

**Comment by jfilter** [comment]
Or make sure `crypto` is installed. But clearing the caches will most likely solve this.

**Comment by jfilter** [comment]
See https://stackoverflow.com/questions/29836434/requiring-unknown-module-crypto-in-react-native-environment

**Comment by guitar9** [comment]
forked it made some changes. For me it works now in react native.

[Link to Fork](https://github.com/guitar9/hafas-client)

**Comment by derhuerst** [comment]
most of the  changes seem unrelated. please try again with the vanilla `hafas-client@2.7.3`.
