### ISSUE TITLE
Trouble with using INSA profile

### ISSUE THREAD

**Issue by jagDanJu** [public-transport/hafas-client#78]
Hey Guys,

on the moment i have a problem with the INSA profile and the /departures endpoint.

With stationId 000005254 and duration: 20 i get an valid result set. 
Try the same with 000005258 and it don´t work. I´m getting the following error:

`TypeError: Cannot read property 'substr' of undefined
    at parseDateTime (..\node_modules\hafas-client\parse\date-time.js:6:22)
    at Object.parseWarning (..\node_modules\hafas-client\parse\warning.js:36:14)
    at d.warnings.c.himL.map.w (..\node_modules\hafas-client\lib\request.js:110:41)
    at Array.map (<anonymous>)
    at fetch.then.then (..\node_modules\hafas-client\lib\request.js:110:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)`

Any Ideas on this?

Greetings Daniel

**Comment by derhuerst** [comment]
Did you pass a specific date & time (`when` option)? Please provide the exact time to help me debug this.

**Comment by jagDanJu** [comment]
@derhuerst Nothing like that.. Just this:

`
client.departures("000005258", {duration: 20})
.then(data => {
    res.send(data)
  })
  .catch(console.error)`

I´am test it right now.

**Comment by derhuerst** [comment]
Published as `hafas-client@3.1.2`! :shipit:

**Comment by jagDanJu** [comment]
Thanks Guy! It work´s fine.
